//This file is automatically generated.
//Do not attempt to make changes to this file because the changes will be erased and overwritten.
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;

namespace OpenDentBusiness.Crud{
	public class SmsFromMobileCrud {
		///<summary>Gets one SmsFromMobile object from the database using the primary key.  Returns null if not found.</summary>
		public static SmsFromMobile SelectOne(long smsFromMobileNum){
			string command="SELECT * FROM smsfrommobile "
				+"WHERE SmsFromMobileNum = "+POut.Long(smsFromMobileNum);
			List<SmsFromMobile> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets one SmsFromMobile object from the database using a query.</summary>
		public static SmsFromMobile SelectOne(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SmsFromMobile> list=TableToList(Db.GetTable(command));
			if(list.Count==0) {
				return null;
			}
			return list[0];
		}

		///<summary>Gets a list of SmsFromMobile objects from the database using a query.</summary>
		public static List<SmsFromMobile> SelectMany(string command){
			if(RemotingClient.RemotingRole==RemotingRole.ClientWeb) {
				throw new ApplicationException("Not allowed to send sql directly.  Rewrite the calling class to not use this query:\r\n"+command);
			}
			List<SmsFromMobile> list=TableToList(Db.GetTable(command));
			return list;
		}

		///<summary>Converts a DataTable to a list of objects.</summary>
		public static List<SmsFromMobile> TableToList(DataTable table){
			List<SmsFromMobile> retVal=new List<SmsFromMobile>();
			SmsFromMobile smsFromMobile;
			for(int i=0;i<table.Rows.Count;i++) {
				smsFromMobile=new SmsFromMobile();
				smsFromMobile.SmsFromMobileNum= PIn.Long  (table.Rows[i]["SmsFromMobileNum"].ToString());
				smsFromMobile.PatNum          = PIn.Long  (table.Rows[i]["PatNum"].ToString());
				smsFromMobile.ClinicNum       = PIn.Long  (table.Rows[i]["ClinicNum"].ToString());
				smsFromMobile.CommlogNum      = PIn.Long  (table.Rows[i]["CommlogNum"].ToString());
				smsFromMobile.MsgText         = PIn.String(table.Rows[i]["MsgText"].ToString());
				smsFromMobile.DateTimeReceived= PIn.DateT (table.Rows[i]["DateTimeReceived"].ToString());
				smsFromMobile.SmsPhoneNumber  = PIn.String(table.Rows[i]["SmsPhoneNumber"].ToString());
				smsFromMobile.MsgPart         = PIn.String(table.Rows[i]["MsgPart"].ToString());
				smsFromMobile.MsgTotal        = PIn.String(table.Rows[i]["MsgTotal"].ToString());
				smsFromMobile.MsgRefID        = PIn.String(table.Rows[i]["MsgRefID"].ToString());
				retVal.Add(smsFromMobile);
			}
			return retVal;
		}

		///<summary>Inserts one SmsFromMobile into the database.  Returns the new priKey.</summary>
		public static long Insert(SmsFromMobile smsFromMobile){
			if(DataConnection.DBtype==DatabaseType.Oracle) {
				smsFromMobile.SmsFromMobileNum=DbHelper.GetNextOracleKey("smsfrommobile","SmsFromMobileNum");
				int loopcount=0;
				while(loopcount<100){
					try {
						return Insert(smsFromMobile,true);
					}
					catch(Oracle.DataAccess.Client.OracleException ex){
						if(ex.Number==1 && ex.Message.ToLower().Contains("unique constraint") && ex.Message.ToLower().Contains("violated")){
							smsFromMobile.SmsFromMobileNum++;
							loopcount++;
						}
						else{
							throw ex;
						}
					}
				}
				throw new ApplicationException("Insert failed.  Could not generate primary key.");
			}
			else {
				return Insert(smsFromMobile,false);
			}
		}

		///<summary>Inserts one SmsFromMobile into the database.  Provides option to use the existing priKey.</summary>
		public static long Insert(SmsFromMobile smsFromMobile,bool useExistingPK){
			if(!useExistingPK && PrefC.RandomKeys) {
				smsFromMobile.SmsFromMobileNum=ReplicationServers.GetKey("smsfrommobile","SmsFromMobileNum");
			}
			string command="INSERT INTO smsfrommobile (";
			if(useExistingPK || PrefC.RandomKeys) {
				command+="SmsFromMobileNum,";
			}
			command+="PatNum,ClinicNum,CommlogNum,MsgText,DateTimeReceived,SmsPhoneNumber,MsgPart,MsgTotal,MsgRefID) VALUES(";
			if(useExistingPK || PrefC.RandomKeys) {
				command+=POut.Long(smsFromMobile.SmsFromMobileNum)+",";
			}
			command+=
				     POut.Long  (smsFromMobile.PatNum)+","
				+    POut.Long  (smsFromMobile.ClinicNum)+","
				+    POut.Long  (smsFromMobile.CommlogNum)+","
				+    DbHelper.ParamChar+"paramMsgText,"
				+    POut.DateT (smsFromMobile.DateTimeReceived)+","
				+"'"+POut.String(smsFromMobile.SmsPhoneNumber)+"',"
				+"'"+POut.String(smsFromMobile.MsgPart)+"',"
				+"'"+POut.String(smsFromMobile.MsgTotal)+"',"
				+"'"+POut.String(smsFromMobile.MsgRefID)+"')";
			if(smsFromMobile.MsgText==null) {
				smsFromMobile.MsgText="";
			}
			OdSqlParameter paramMsgText=new OdSqlParameter("paramMsgText",OdDbType.Text,POut.StringNote(smsFromMobile.MsgText));
			if(useExistingPK || PrefC.RandomKeys) {
				Db.NonQ(command,paramMsgText);
			}
			else {
				smsFromMobile.SmsFromMobileNum=Db.NonQ(command,true,paramMsgText);
			}
			return smsFromMobile.SmsFromMobileNum;
		}

		///<summary>Updates one SmsFromMobile in the database.</summary>
		public static void Update(SmsFromMobile smsFromMobile){
			string command="UPDATE smsfrommobile SET "
				+"PatNum          =  "+POut.Long  (smsFromMobile.PatNum)+", "
				+"ClinicNum       =  "+POut.Long  (smsFromMobile.ClinicNum)+", "
				+"CommlogNum      =  "+POut.Long  (smsFromMobile.CommlogNum)+", "
				+"MsgText         =  "+DbHelper.ParamChar+"paramMsgText, "
				+"DateTimeReceived=  "+POut.DateT (smsFromMobile.DateTimeReceived)+", "
				+"SmsPhoneNumber  = '"+POut.String(smsFromMobile.SmsPhoneNumber)+"', "
				+"MsgPart         = '"+POut.String(smsFromMobile.MsgPart)+"', "
				+"MsgTotal        = '"+POut.String(smsFromMobile.MsgTotal)+"', "
				+"MsgRefID        = '"+POut.String(smsFromMobile.MsgRefID)+"' "
				+"WHERE SmsFromMobileNum = "+POut.Long(smsFromMobile.SmsFromMobileNum);
			if(smsFromMobile.MsgText==null) {
				smsFromMobile.MsgText="";
			}
			OdSqlParameter paramMsgText=new OdSqlParameter("paramMsgText",OdDbType.Text,POut.StringNote(smsFromMobile.MsgText));
			Db.NonQ(command,paramMsgText);
		}

		///<summary>Updates one SmsFromMobile in the database.  Uses an old object to compare to, and only alters changed fields.  This prevents collisions and concurrency problems in heavily used tables.  Returns true if an update occurred.</summary>
		public static bool Update(SmsFromMobile smsFromMobile,SmsFromMobile oldSmsFromMobile){
			string command="";
			if(smsFromMobile.PatNum != oldSmsFromMobile.PatNum) {
				if(command!=""){ command+=",";}
				command+="PatNum = "+POut.Long(smsFromMobile.PatNum)+"";
			}
			if(smsFromMobile.ClinicNum != oldSmsFromMobile.ClinicNum) {
				if(command!=""){ command+=",";}
				command+="ClinicNum = "+POut.Long(smsFromMobile.ClinicNum)+"";
			}
			if(smsFromMobile.CommlogNum != oldSmsFromMobile.CommlogNum) {
				if(command!=""){ command+=",";}
				command+="CommlogNum = "+POut.Long(smsFromMobile.CommlogNum)+"";
			}
			if(smsFromMobile.MsgText != oldSmsFromMobile.MsgText) {
				if(command!=""){ command+=",";}
				command+="MsgText = "+DbHelper.ParamChar+"paramMsgText";
			}
			if(smsFromMobile.DateTimeReceived != oldSmsFromMobile.DateTimeReceived) {
				if(command!=""){ command+=",";}
				command+="DateTimeReceived = "+POut.DateT(smsFromMobile.DateTimeReceived)+"";
			}
			if(smsFromMobile.SmsPhoneNumber != oldSmsFromMobile.SmsPhoneNumber) {
				if(command!=""){ command+=",";}
				command+="SmsPhoneNumber = '"+POut.String(smsFromMobile.SmsPhoneNumber)+"'";
			}
			if(smsFromMobile.MsgPart != oldSmsFromMobile.MsgPart) {
				if(command!=""){ command+=",";}
				command+="MsgPart = '"+POut.String(smsFromMobile.MsgPart)+"'";
			}
			if(smsFromMobile.MsgTotal != oldSmsFromMobile.MsgTotal) {
				if(command!=""){ command+=",";}
				command+="MsgTotal = '"+POut.String(smsFromMobile.MsgTotal)+"'";
			}
			if(smsFromMobile.MsgRefID != oldSmsFromMobile.MsgRefID) {
				if(command!=""){ command+=",";}
				command+="MsgRefID = '"+POut.String(smsFromMobile.MsgRefID)+"'";
			}
			if(command==""){
				return false;
			}
			if(smsFromMobile.MsgText==null) {
				smsFromMobile.MsgText="";
			}
			OdSqlParameter paramMsgText=new OdSqlParameter("paramMsgText",OdDbType.Text,POut.StringNote(smsFromMobile.MsgText));
			command="UPDATE smsfrommobile SET "+command
				+" WHERE SmsFromMobileNum = "+POut.Long(smsFromMobile.SmsFromMobileNum);
			Db.NonQ(command,paramMsgText);
			return true;
		}

		///<summary>Deletes one SmsFromMobile from the database.</summary>
		public static void Delete(long smsFromMobileNum){
			string command="DELETE FROM smsfrommobile "
				+"WHERE SmsFromMobileNum = "+POut.Long(smsFromMobileNum);
			Db.NonQ(command);
		}

	}
}